//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerWebServices.MyRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProdIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProdId {
            get {
                return this.ProdIdField;
            }
            set {
                if ((this.ProdIdField.Equals(value) != true)) {
                    this.ProdIdField = value;
                    this.RaisePropertyChanged("ProdId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyRef.LPUWebServiceSoap")]
    public interface LPUWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsumerWebServices.MyRef.HelloWorldResponse HelloWorld(ConsumerWebServices.MyRef.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumerWebServices.MyRef.HelloWorldResponse> HelloWorldAsync(ConsumerWebServices.MyRef.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMe", ReplyAction="*")]
        int AddMe(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMe", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddMeAsync(int num1, int num2);
        
        // CODEGEN: Generating message contract since element name ShowAllProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllProducts", ReplyAction="*")]
        ConsumerWebServices.MyRef.ShowAllProductsResponse ShowAllProducts(ConsumerWebServices.MyRef.ShowAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumerWebServices.MyRef.ShowAllProductsResponse> ShowAllProductsAsync(ConsumerWebServices.MyRef.ShowAllProductsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsumerWebServices.MyRef.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsumerWebServices.MyRef.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumerWebServices.MyRef.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsumerWebServices.MyRef.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowAllProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowAllProducts", Namespace="http://tempuri.org/", Order=0)]
        public ConsumerWebServices.MyRef.ShowAllProductsRequestBody Body;
        
        public ShowAllProductsRequest() {
        }
        
        public ShowAllProductsRequest(ConsumerWebServices.MyRef.ShowAllProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowAllProductsRequestBody {
        
        public ShowAllProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowAllProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowAllProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumerWebServices.MyRef.ShowAllProductsResponseBody Body;
        
        public ShowAllProductsResponse() {
        }
        
        public ShowAllProductsResponse(ConsumerWebServices.MyRef.ShowAllProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowAllProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumerWebServices.MyRef.Product[] ShowAllProductsResult;
        
        public ShowAllProductsResponseBody() {
        }
        
        public ShowAllProductsResponseBody(ConsumerWebServices.MyRef.Product[] ShowAllProductsResult) {
            this.ShowAllProductsResult = ShowAllProductsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LPUWebServiceSoapChannel : ConsumerWebServices.MyRef.LPUWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LPUWebServiceSoapClient : System.ServiceModel.ClientBase<ConsumerWebServices.MyRef.LPUWebServiceSoap>, ConsumerWebServices.MyRef.LPUWebServiceSoap {
        
        public LPUWebServiceSoapClient() {
        }
        
        public LPUWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LPUWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LPUWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LPUWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumerWebServices.MyRef.HelloWorldResponse ConsumerWebServices.MyRef.LPUWebServiceSoap.HelloWorld(ConsumerWebServices.MyRef.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsumerWebServices.MyRef.HelloWorldRequest inValue = new ConsumerWebServices.MyRef.HelloWorldRequest();
            inValue.Body = new ConsumerWebServices.MyRef.HelloWorldRequestBody();
            ConsumerWebServices.MyRef.HelloWorldResponse retVal = ((ConsumerWebServices.MyRef.LPUWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumerWebServices.MyRef.HelloWorldResponse> ConsumerWebServices.MyRef.LPUWebServiceSoap.HelloWorldAsync(ConsumerWebServices.MyRef.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumerWebServices.MyRef.HelloWorldResponse> HelloWorldAsync() {
            ConsumerWebServices.MyRef.HelloWorldRequest inValue = new ConsumerWebServices.MyRef.HelloWorldRequest();
            inValue.Body = new ConsumerWebServices.MyRef.HelloWorldRequestBody();
            return ((ConsumerWebServices.MyRef.LPUWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int AddMe(int num1, int num2) {
            return base.Channel.AddMe(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> AddMeAsync(int num1, int num2) {
            return base.Channel.AddMeAsync(num1, num2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumerWebServices.MyRef.ShowAllProductsResponse ConsumerWebServices.MyRef.LPUWebServiceSoap.ShowAllProducts(ConsumerWebServices.MyRef.ShowAllProductsRequest request) {
            return base.Channel.ShowAllProducts(request);
        }
        
        public ConsumerWebServices.MyRef.Product[] ShowAllProducts() {
            ConsumerWebServices.MyRef.ShowAllProductsRequest inValue = new ConsumerWebServices.MyRef.ShowAllProductsRequest();
            inValue.Body = new ConsumerWebServices.MyRef.ShowAllProductsRequestBody();
            ConsumerWebServices.MyRef.ShowAllProductsResponse retVal = ((ConsumerWebServices.MyRef.LPUWebServiceSoap)(this)).ShowAllProducts(inValue);
            return retVal.Body.ShowAllProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumerWebServices.MyRef.ShowAllProductsResponse> ConsumerWebServices.MyRef.LPUWebServiceSoap.ShowAllProductsAsync(ConsumerWebServices.MyRef.ShowAllProductsRequest request) {
            return base.Channel.ShowAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumerWebServices.MyRef.ShowAllProductsResponse> ShowAllProductsAsync() {
            ConsumerWebServices.MyRef.ShowAllProductsRequest inValue = new ConsumerWebServices.MyRef.ShowAllProductsRequest();
            inValue.Body = new ConsumerWebServices.MyRef.ShowAllProductsRequestBody();
            return ((ConsumerWebServices.MyRef.LPUWebServiceSoap)(this)).ShowAllProductsAsync(inValue);
        }
    }
}
